- hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: Ensure VM service remved
      k8s:
        state: absent
        api_version: v1
        kind: Service
        namespace: "{{ namespace }}"
        name: "{{ service_name }}"
        wait: yes
        
    - name: Remove the VirtualMachineExport Token
      k8s:
        state: absent
        apiVersion: v1
        kind: Secret
        namespace: "{{ namespace }}"
        name: vmexport-token-{{ vm_name }}
        wait: yes
