- hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: Ensure VM service removed
      k8s:
        state: absent
        api_version: v1
        kind: Service
        namespace: "{{ namespace }}"
        name: "{{ service_name }}"
        wait: yes
        
    - name: Remove the VirtualMachineExport Token
      k8s:
        state: absent
        api_version: v1
        kind: Secret
        namespace: "{{ namespace }}"
        name: vmexport-token-{{ vm_name }}
        wait: yes

    - name: Get list of PVCs
      k8s_info:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: "{{ namespace }}"
      register: pvc_list

    - name: Filter out the PVC used by this PipeLineRun as its workspace
      set_fact:
        filtered_pvcs: "{{ pvc_list.resources | json_query(jmespath_expr) }}"
      vars:
        jmespath_expr: "[?metadata.ownerReferences[0].uid == `{{ pipelinerun_uid }}`]"

    - name: Delete the PVCs used by this PipeLineRun
      k8s:
        api_version: v1
        kind: PersistentVolumeClaim
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace }}"
        state: absent
      loop: "{{ filtered_pvcs }}"
      
    - name: Reset finalizers of deleted PVCs
      kubernetes.core.k8s_json_patch:
        kind: PersistentVolumeClaim
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace }}"
        patch:
          - op: replace
            path: /metadata/finalizers
            value: []
      loop: "{{ filtered_pvcs }}"
