- hosts: localhost
  connection: local
  collections:
    - kubernetes.core
  tasks:
    - name: Ensure VM service removed
      k8s:
        state: absent
        api_version: v1
        kind: Service
        namespace: "{{ namespace }}"
        name: "{{ service_name }}"
        wait: yes

    - name: Remove the VirtualMachineExport Token
      k8s:
        state: absent
        api_version: v1
        kind: Secret
        namespace: "{{ namespace }}"
        name: vmexport-token-{{ vm_name }}
        wait: yes

    - name: Get list of PVCs
      k8s_info:
        api_version: v1
        kind: PersistentVolumeClaim
        namespace: "{{ namespace }}"
      register: pvc_list

    - name: Delete the PVCs used by this PipeLineRun
      k8s:
        api_version: v1
        kind: PersistentVolumeClaim
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace }}"
        state: absent
      loop: "{{ pvc_list.resources }}"
      when: "item.metadata.ownerReferences is defined and item.metadata.ownerReferences[0].uid == pipelinerun_uid"

    - name: Reset finalizers of deleted PVCs
      kubernetes.core.k8s_json_patch:
        kind: PersistentVolumeClaim
        name: "{{ item.metadata.name }}"
        namespace: "{{ item.metadata.namespace }}"
        patch:
          - op: replace
            path: /metadata/finalizers
            value: []
      loop: "{{ pvc_list.resources }}"
      when: "item.metadata.ownerReferences is defined and item.metadata.ownerReferences[0].uid == pipelinerun_uid"
