- hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: Create a new Service
      k8s:
        state: present
        resource_definition: |
          apiVersion: v1
          kind: Service
          metadata:
            name: $(tasks.create-vm-from-template.results.name)
            namespace: $(tasks.create-vm-from-template.results.namespace)
          spec:
            selector:
              kubevirt.io/domain: $(tasks.create-vm-from-template.results.name)
            ports:
            - port: $(params.svcPort)
              targetPort: $(params.svcPort)
        wait: yes
      register: svc
    - name: Get the Service
      k8s_info:
        kind: Service
        namespace: $(tasks.create-vm-from-template.results.namespace)
      register: service_list
    - name: Log Service Details
      debug:
        msg: "{{ item | json_query('metadata.name') }}"
      loop: '{{service_list.resources}}'
      loop_control:
        label: "Service (Namespace: {{item | json_query('metadata.namespace')}})"
