- hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: Create a new Service
      k8s:
        state: present
        resource_definition: |
          apiVersion: v1
          kind: Service
          metadata:
            name: "{{ service_name }}"
            namespace: "{{ namespace }}"
          spec:
            selector:
              kubevirt.io/domain: "{{ service_selector_label_value }}"
            ports:
            - port: 5986
              targetPort: 5986
        wait: yes
      register: svc
    - name: Get the Service
      k8s_info:
        kind: Service
        namespace: $(tasks.create-vm-from-template.results.namespace)
      register: service_list
    - name: Log Service Details
      debug:
        msg: "{{ item | json_query('metadata.name') }}"
      loop: '{{service_list.resources}}'
      loop_control:
        label: "Service (Namespace: {{item | json_query('metadata.namespace')}})"
