---
- hosts: all
  gather_facts: no
  tasks:
    - name: Wait for Windows vm to be reachable over WinRM
      wait_for_connection:
        delay: 1
        timeout: 300
    - name: Ensure IIS is installed
      win_feature:
        name: "Web-Server"
        state: present
        restart: no
        include_sub_features: yes
        include_management_tools: yes
