- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.kubernetes
  tasks:
    - name: Generate a new virtual disk download token
      set_fact:
        token: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"

    - name: Create a new VirtualMachineExport Token
      k8s:
        state: present
        resource_definition: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: vmexport-token-{{ vm_name }}
            namespace: {{ namespace }}
          stringData:
            token: "{{ token }}"
        wait: yes
      
    - name: Create a new VirtualMachineExport object
      k8s:
        state: present
        resource_definition: |
          apiVersion: export.kubevirt.io/v1alpha1
          kind: VirtualMachineExport
          metadata:
            name: vmexport-{{ vm_name }}
            namespace: {{ namespace }}
          spec:
            tokenSecretRef: vmexport-token-{{ vm_name }}
            source:
              apiGroup: ""
              kind: PersistentVolumeClaim
              name: {{ pvc_name }}
        wait: yes
        wait_condition:
          reason: PodReady
          status: "True"
          type: Ready
        
    - name: Get the VirtualMachineExport object
      k8s_info:
        api_version: export.kubevirt.io/v1alpha1
        kind: VirtualMachineExport
        namespace: "{{ namespace }}"
        name: vmexport-{{ vm_name }}
      register: vmexport
      
    - name: Get virtual disk download url
      set_fact:
        download_url: "{{ (vmexport | json_query(jmesquery))[0] }}"
      vars:
         jmesquery: resources[0].status.links.internal.volumes[0].formats[?format=='raw'].url
         
    - name: Print download url
      debug:
        var: download_url

    - name: Ensure download directory exists
      ansible.builtin.file:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/files"
        state: directory
        mode: "0755"
        
    - name: Download aria2 rpm package
      ansible.builtin.get_url:
        url: https://archive.fedoraproject.org/pub/epel/8/Everything/x86_64/Packages/a/aria2-1.35.0-2.el8.x86_64.rpm
        dest: /tmp/aria2-1.35.0-2.el8.x86_64.rpm
        mode: '0664'
        
    - name: Install aria2 rpm package
      yum:
        name: /tmp/aria2-1.35.0-2.el8.x86_64.rpm
        state: present
        disable_gpg_check: yes
        
#    - name: Download virtual disk file
#      ansible.builtin.command:
#        cmd: curl -k -H "x-kubevirt-export-token:{{ token }}" "{{ download_url }}" --output "{{ lookup('ansible.builtin.env', 'HOME') }}/files/disk.img"
#        creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/files/disk.img"
      
    - name: Download virtual disk file
      ansible.builtin.command:
        cmd: aria2c --max-connection-per-server=5 --split=5 --quiet --check-certificate=false --header="x-kubevirt-export-token:{{ token }}" -o "{{ lookup('ansible.builtin.env', 'HOME') }}/files/disk.img" "{{ download_url }}"
        creates: "{{ lookup('ansible.builtin.env', 'HOME') }}/files/disk.img"
      
    - name: Get stats of the downloaded virtual disk file
      ansible.builtin.stat:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/files/disk.img"
      register: st

    - name: Print virtual disk info
      debug:
        var: st
