- hosts: localhost
  connection: local
  gather_facts: no
  collections:
    - community.kubernetes
  vars:
    token: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"
  tasks:
    - name: Create a new VirtualMachineExport Token
      k8s:
        state: present
        resource_definition: |
          apiVersion: v1
          kind: Secret
          metadata:
            name: vmexport-token-{{ vm_name }}
            namespace: {{ namespace }}
          stringData:
            token: "{{ token }}"
        wait: yes
      register: secret
    - name: Create a new VirtualMachineExport object
      k8s:
        state: present
        resource_definition: |
          apiVersion: export.kubevirt.io/v1alpha1
          kind: VirtualMachineExport
          metadata:
            name: vmexport-{{ vm_name }}
            namespace: {{ namespace }}
          spec:
            tokenSecretRef: vmexport-token-{{ vm_name }}
            source:
              apiGroup: ""
              kind: PersistentVolumeClaim
              name: {{ pvc_name }}
        wait: yes
        
    - name: Get the VirtualMachineExport object
      k8s_info:
        api_version: export.kubevirt.io/v1alpha1
        kind: VirtualMachineExport
        namespace: "{{ namespace }}"
        name: vmexport-{{ vm_name }}
      register: vmexport
      
    - name: Get virtual disk download url
      set_fact:
        download_url: "{{ (vmexport | json_query(jmesquery))[0] }}"
      vars:
         jmesquery: resources[0].status.links.internal.volumes[0].formats[?format=='raw'].url
         
    - name: Print download url
      debug:
        var: download_url

    - name: Ensure download directory exists
      ansible.builtin.file:
        path: "{{ lookup('ansible.builtin.env', 'HOME') }}/files"
        state: directory
        mode: "0755"
        
    - name: Download virtual disk file
      ansible.builtin.get_url:
        url: "{{ download_url }}"
        dest: "{{ lookup('ansible.builtin.env', 'HOME') }}/files/disk.img"
        headers:
          x-kubevirt-export-token: "{{ token }}"
        validate_certs: no
